### ISSUE TITLE
Module not found: Can't resolve './build/Release/iselevated'

### ISSUE THREAD

**Issue by kmturley** [arkon/native-is-elevated#17]
I have a core package `myapp-core` which has `native-is-elevated` as a dependency. Everything builds and runs fine.
```
myapp
|--myapp-core
   |--native-is-elevated
```

However when I then install `myapp-core` as a dependency of `myapp`, I get a runtime error:
```
Module not found: Can't resolve './build/Release/iselevated' in '/Users/username/Sites/myapp/node_modules/native-is-elevated'
```

It appears that the path `./build/Release/iselevated` is not resolving for nested dependencies.

Should this path be defined using [__filename](https://nodejs.org/docs/latest/api/modules.html#modules_filename) and [__dirname](https://nodejs.org/docs/latest/api/modules.html#modules_dirname) variables?

All paths should also be cross-platform safe using `path.join()`?

**Comment by arkon** [comment]
That seems a bit odd. Do you see the `build/Release` folder somewhere within the `native-is-elevated` folder?

**Comment by kmturley** [comment]
Its odd because that part of the code shouldn't even be run on a Mac:
```
import isElevated from 'native-is-elevated';

function isAdmin(): boolean {
  if (process.platform === 'win32') {
    return isElevated();
  } else {
    return process.getuid() === 0;
  }
}
```
I guess the `require()` is being processed when the module is imported via TypeScript.

I see VSCode using a different `import` method, perhaps to get around this issue?
```
async isAdmin(): Promise<boolean> {
  let isAdmin: boolean;
  if (isWindows) {
    isAdmin = (await import('native-is-elevated'))();
  } else {
    isAdmin = process.getuid() === 0;
  }
  return isAdmin;
}
```
https://github.com/microsoft/vscode/blob/aa8de90777638b4777173f6211c69cb41dbb7103/src/vs/platform/native/electron-main/nativeHostMainService.ts#L469

However when I try that same approach it shows:
<img width="626" alt="Screen Shot 2022-04-02 at 12 04 41 PM" src="https://user-images.githubusercontent.com/1710493/161397680-7ee03ae6-b034-4868-9c1d-94028d1e125f.png">

Could you provide guidance for use with TypeScript and cross-platform machines?

**Comment by kmturley** [comment]
Changing the code to:
```
async function isAdmin(): Promise<boolean> {
  if (process.platform === 'win32') {
    return (await import('native-is-elevated')).default();
  } else {
    return process.getuid() === 0;
  }
}
```

Has allowed TypeScript to validate the await import.

However the error still persists. Node module is there and in the correct place
<img width="709" alt="Screen Shot 2022-04-02 at 1 35 42 PM" src="https://user-images.githubusercontent.com/1710493/161400348-78348006-b790-4a60-b33e-8e19690fdb3b.png">

**Comment by kmturley** [comment]
Found the issue. NextJS has overlapping boundaries between Server/Browser rendering which can cause these issues.

I was importing another method from the same file for use in the browser:
```
import { methodA } from '@myapp/core/dist/utils';
```

Which meant NextJS was compiling the module into a browser distribution.
Not your issue, closing
