### ISSUE TITLE
Lookup only once and then cached?

### ISSUE THREAD

**Issue by bpasero** [arkon/native-is-elevated#2]
@arkon briefly checking [`index.js `](https://github.com/arkon/native-is-elevated/blob/master/index.js) I would have expected the result of the check for being admin or not to get cached after the first call and then used from there always. Afaik the result can not change in the current process so imho it would be safer (and faster) to cache the result.

It seems to be cached [here](https://github.com/arkon/native-is-elevated/blob/master/index.js#L15) in case we found out that the process is not running as admin, but why is the call still being made otherwise?

**Comment by arkon** [comment]
@bpasero That check is actually to check if the module was imported properly, and is modelled off of [node-windows-foreground-love](https://github.com/the-ress/node-windows-foreground-love).

You are right about the value likely not changing after the fact though, probably. The only thing I can think of is a new process somehow being forked or spawned but with elevated processes (somehow — I have no idea if that's actually possible).

**Comment by bpasero** [comment]
@arkon but that new process will get a new javascript context and so you should be OK. there is no way I can forsee where a process would change its elevation level without restarting.

**Comment by arkon** [comment]
@bpasero Yup, that makes sense. I've published v0.2.0 that returns a cached return value.

**Comment by bpasero** [comment]
Awesome!
