### ISSUE TITLE
Incorrectly detects a Windows user as an admin when UAC is disabled

### ISSUE THREAD

**Issue by montoner0** [arkon/native-is-elevated#20]
I'm working under an unprivileged user account and can't elevate it because UAC is disabled, though this module (as part of VSCode) shows that it's running under admin. More info in the [VSCode issue](https://github.com/microsoft/vscode/issues/173698)

**Comment by arkon** [comment]
You mention in the other issue that this is non-reproducible in a clean VM. If you figure out how to reproduce it, then please post those steps.

**Comment by montoner0** [comment]
Well, I can reproduce it every time on my machine. So I've made a bit of research and found another [SO answer](https://stackoverflow.com/questions/4230602/detect-if-program-is-running-with-full-administrator-rights) with a slightly different approach. 

Here are two examples which successfully detect elevated process on my machine with disabled UAC and on another machine with enabled UAC.

```
#include <Windows.h>
#include <Shlobj.h>

BOOL IsElevated2() {
    BOOL isMember = FALSE;
    PSID administratorsGroup = NULL;
    SID_IDENTIFIER_AUTHORITY SIDAuthNT = SECURITY_NT_AUTHORITY;

    if (AllocateAndInitializeSid(&SIDAuthNT, 2, SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ADMINS,
        0, 0, 0, 0, 0, 0, &administratorsGroup)) {
        CheckTokenMembership(nullptr, administratorsGroup, &isMember);
    }

    if(administratorsGroup){
        FreeSid(administratorsGroup);
    }

    return isMember;
}

BOOL IsElevated3() {
    return IsUserAnAdmin();
}
```

**Comment by montoner0** [comment]
Are there any plans about this issue?

**Comment by arkon** [comment]
I don't have a Windows dev env readily available anymore, so I'll need to set one up at some point.

**Comment by montoner0** [comment]
Can I help somehow with this? The bug is annoying.
